config/routes.rb
Rails.application.routes.draw do
  resources :playlists do
    resources :songs
  end
  resources :songs, only: [:show]
  get '/auth/spotify/callback', to: 'users#spotify'
  resources :home
  root "application#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/playlist.rb
class Playlist < ApplicationRecord
    has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
    belongs_to :playlist
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
  end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
    def index
        @playlists = Playlist.includes(:songs).all
    end

    def show
        @playlist = Playlist.find(params[:id])
    end


end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
    def show
      @song = Song.find(params[:id])
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def spotify
    Song.destroy_all
    Playlist.destroy_all
    spotify_user = RSpotify::User.new(request.env['omniauth.auth'])

    spotify_user.playlists.each do |spotify_playlist|
      playlist = Playlist.create(name: spotify_playlist.name, spotify_id: spotify_playlist.id)

      offset = 0
      limit = 100
      while (tracks = spotify_playlist.tracks(limit: limit, offset: offset)) && tracks.any?
        tracks.each do |track|
          playlist.songs << Song.create(name: track.name, spotify_id: track.id, artist_name: track.artists.first.name, song_image: track.album.images.first['url'])
        end
        offset += limit
      end
    end

    redirect_to playlists_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<%= link_to 'Sign in with Spotify', '/auth/spotify', method: :post %>

app/views/layouts/_flash.html.erb
<% if flash[:error] %>
  <div class="alert alert-danger alert-dismissible fade show">
    <%= flash[:error] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% elsif flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="mt-4" style="background-color: #000000; color: wheat; position: fixed; bottom: 0; width: 100%; text-align: center; padding: 10px;">
  <p class="mb-0">Copyright © 2024 SpoTabs</p>
</footer>

app/views/layouts/_navbar.html.erb
<style>
    nav {
      background-color: #000000;
    }

    .navbar-brand {
      font-weight: 700;
      color: wheat !important;
    }

    .navbar-nav .nav-link{
      color: wheat !important;
    }
</style>

<nav class="navbar navbar-expand-lg fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">SpoTabs</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="board" href="/">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Playlists', playlists_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boardify</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

    <style>
      body {
        font-family: "Roboto", sans-serif;
        background-color: #2b2b2b;
        color: #ddd;
      }
      .content {
        padding-top: 80px;
        padding-bottom: 80px;
      }
    </style>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="content">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/playlists/index.html.erb
<div class="container">
  <div class="row align-items-center">
    <% @playlists.each do |playlist| %>
      <div class="col-sm-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= playlist.name %></h5>
            <p class="card-text">This playlist has <%= playlist.songs.count %> songs.</p>
            <%= link_to 'View Playlist', playlist_path(playlist), class: 'btn btn-dark' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/playlists/show.html.erb
<h1 class="text-center"><%= @playlist.name %> <%= link_to 'Back', playlists_path, class: 'btn btn-secondary' %></h1>
<h2 class="text-center">Songs:</h2>
<div class="container">
  <div class="row">
    <% @playlist.songs.each do |song| %>
      <div class="col-sm-2">
        <div class="card" style="width: 12rem;">
          <%= link_to song_path(song, playlist_id: @playlist.id) do %>
            <img src="<%= song.song_image %>" class="card-img-top" alt="<%= song.name %>" style="width: 100%; max-width: 200px;">
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= song.name %></h5>
            <p><%= song.artist_name %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/songs/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="<%= @song.song_image %>" alt="<%= @song.name %>" style="width: 100%; max-width: 500px;">
        </div>
        <div class="col-md-6">
            <h1 class="text-center"><%= @song.name %></h1>
            <h2 class="text-center"><%= @song.artist_name %></h2>
            <h3 class="mb-1 text-center">Tabs:</h3>
            <div class="text-center">
                <%= link_to 'Songsterr', "https://www.songsterr.com/?pattern=#{@song.name}", class: 'btn btn-primary ' %>
                <%= link_to 'Ultimate Guitar', "https://www.ultimate-guitar.com/search.php?search_type=title&value=#{@song.name}", class: 'btn btn-warning' %>
            </div>
            <div class="text-center">
                <%= link_to 'Back', playlist_path(params[:playlist_id]), class: 'btn btn-secondary' %>
            </div>
        </div>
    </div>
</div>